version: '3'

services:
  laravel-app:
    build:
      context: .
      dockerfile: ./e-bookstore-laravel-backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db

  react-app:
    build:
      context: .
      dockerfile: ./e-bookstore-react-frontend/Dockerfile
    ports:
      - "3000:3000"

  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "" 
      MYSQL_USER: root
      MYSQL_PASSWORD: "" 
      MYSQL_DATABASE: e_bookstore
    volumes:
      - ./database:/docker-entrypoint-initdb.d 
    ports:
      - "3306:3306" 
      
      
      
